/**
 * אוצר המילים של אירועי הלוג, מילה במילה מסעיף 26 ודרישה 14 באפיון.
 *
 * הרשימה קפואה ומיוצאת כדי שקוד לא יוכל להמציא שם אירוע חדש בשקט —
 * assertKnownEvent נכשל על שם שלא מופיע כאן.
 */
export const EVENTS = Object.freeze({
    CALL_STARTED: 'CALL_STARTED',
    CALL_REJECTED_UNAUTHORIZED: 'CALL_REJECTED_UNAUTHORIZED',
    RECORDING_STARTED: 'RECORDING_STARTED',
    RECORDING_RECEIVED: 'RECORDING_RECEIVED',
    RECORDING_DOWNLOADED: 'RECORDING_DOWNLOADED',
    RECORDING_ARCHIVED: 'RECORDING_ARCHIVED',
    TRANSCRIPTION_STARTED: 'TRANSCRIPTION_STARTED',
    TRANSCRIPTION_COMPLETED: 'TRANSCRIPTION_COMPLETED',
    TRANSCRIPTION_FAILED: 'TRANSCRIPTION_FAILED',
    PARSER_STARTED: 'PARSER_STARTED',
    PARSER_COMPLETED: 'PARSER_COMPLETED',
    PARSER_FAILED: 'PARSER_FAILED',
    CONFIRMATION_REQUESTED: 'CONFIRMATION_REQUESTED',
    CONFIRMED: 'CONFIRMED',
    RE_RECORD_REQUESTED: 'RE_RECORD_REQUESTED',
    CLARIFICATION_REQUESTED: 'CLARIFICATION_REQUESTED',
    NOTE_SAVED: 'NOTE_SAVED',
    REMINDER_CREATED: 'REMINDER_CREATED',
    REMINDER_CALL_STARTED: 'REMINDER_CALL_STARTED',
    REMINDER_CALL_NO_ANSWER: 'REMINDER_CALL_NO_ANSWER',
    REMINDER_COMPLETED: 'REMINDER_COMPLETED',
    REMINDER_SNOOZED: 'REMINDER_SNOOZED',
    REMINDER_WAITING: 'REMINDER_WAITING',
    REMINDER_INBOX_OFFERED: 'REMINDER_INBOX_OFFERED',
    REMINDER_INBOX_SKIPPED: 'REMINDER_INBOX_SKIPPED',
    REMINDER_REPLAYED_ORIGINAL: 'REMINDER_REPLAYED_ORIGINAL',
    REMINDER_CANCELLED: 'REMINDER_CANCELLED',
    MIRROR_WRITE_QUEUED: 'MIRROR_WRITE_QUEUED',
    MIRROR_WRITE_COMPLETED: 'MIRROR_WRITE_COMPLETED',
    MIRROR_WRITE_FAILED: 'MIRROR_WRITE_FAILED',
    DUPLICATE_REQUEST_IGNORED: 'DUPLICATE_REQUEST_IGNORED',
    CALL_ENDED: 'CALL_ENDED',
    ERROR: 'ERROR'
});

const KNOWN = new Set(Object.values(EVENTS));

export function assertKnownEvent (event) {
    if (!KNOWN.has(event)) {
        throw new Error(`אירוע לוג לא מוכר: "${event}". יש להוסיף אותו ל-src/logging/events.js`);
    }
}
